# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/configuration/all/
# -------------------------------------------------------------------------------------

# website title
title = ""
# Hostname (and path) to the root
baseURL = "http://localhost:1313"
# theme list
# theme = ["FixIt"] # enable in your site config file
# determines default content language ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"
# Do Not add url prefix for default language
defaultContentLanguageInSubdir = false
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false

[languages]
  [languages.zh-cn]
    languageCode = "zh-CN"
    languageName = "简体中文"
    weight = 1 # The Smaller the higher

  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    weight = 2

# copyright description used only for seo schema
copyright = ""
# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true
# the main sections of a site
# if set, the MainSections method on the Site object returns the given sections,
# otherwise it returns the section with the most pages.
# mainSections = ["posts"]


[params.page.comment]
enable = true
[params.page.comment.giscus]
    enable = true
    repo = "zhibinyang/blog"
    repoId = "R_kgDORF7SlA"
    category = "Announcements"
    categoryId = "DIC_kwDORF7SlM4C1vT_"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    lazyLoad = true
    lang = "en"
    darkTheme = "dark"
    lightTheme = "light"