# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

[page]
posts = "/posts/:filename/"

[section]
posts = "/posts/"

[taxonomy]

[term]
