description = "This is my new Hugo FixIt site"
keywords = ["Hugo", "FixIt"]

[author]
name = "Zhibin Yang"
email = ""
link = "https://github.com/zhibinyang"
avatar = "https://avatars.githubusercontent.com/u/13515560"

[app]
title = "Zhibin Yangâ€˜s Blog"

[header]

[header.title]
logo = "/images/fixit.min.svg"

[home]

[home.profile]
enable = true

[customPartials]
head = [
  "inject/fixit-docs-bookmark.html",
]
