description = "This is my new Hugo FixIt site"
keywords = ["Hugo", "FixIt"]

[author]
#name = ""
#email = ""
#link = ""
#avatar = ""

[app]
#title = "Zhibin Yangâ€˜s Blog"

[header]

[header.title]
logo = "logo/logo.png"

[home]

[home.profile]
enable = true

[customPartials]
head = [
  "inject/fixit-docs-bookmark.html",
]
