description = "This is my Blog"
keywords = ["Hugo", "FixIt"]

[author]
#name = "Lruihao"
#email = ""
#link = "https://github.com/Lruihao"
#avatar = "https://lruihao.cn/images/avatar.jpg"

[app]
#title = "Zhibin Yang's Blog"

[header]

[header.title]
logo = "/images/fixit.min.svg"

[home]

[home.profile]
enable = true

[customPartials]
head = [
  "inject/fixit-docs-bookmark.html",
  "inject/gtm-head.html"
]

assets = [
  "inject/gtm-body.html"
]